### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by kennethlimcp** [chuank/particle-offline-compiler#1]
- [x] Add example command to launch atom from terminal

eg. `open -a "/Applications/Atom.app"`
- [x] DFU doesn't seem to list for mine on **Mac OSx 10.9.5**
- [ ] Need to specify a settings file or it's confusing where to go to change the settings. Docs or settings file
- [ ] Compile and OTA is fairly straight forward.You don't need to specify the deviceType.
  Either invoke **particle-cli** or use the API endpoint but particle-dev already does that.  This tool should be a particle-dev add-on

**Comment by chuank** [comment]
1. Sounds good. Yes, documentation is certainly due.
2. Do you mean it does not list any connected DFU serial devices for you?
3. I can consider specifying a json file in the package for easier access to settings, right now it's done through the standard atom package settings view
4. Yes, I'm intending to use particle-cli to invoke ota. Waiting for when Photons can OTA locally before updating this though. Is this possible already? Settings should also allow for the user to enter their local cloud config name as set in particle-cli

**Comment by chuank** [comment]
In readme.md, I wrote about the current issues impacting Particle Dev for non-Particle.io cloud users who deploy their own local clouds, either by design constraint or preference. I hope Dev will implement similar features soon, as they have been noted as enhancements to implement in the future. So this package is an interim measure to fill the gap.

Many of us are researching or developing actual projects with real constraints (firewalled, spotty, networks, TLS, etc). Working via Build / Dev (as described in readme.md) is not the smoothest experience for 'off-gridders'. This is not the perfect solution either but I think it helps a little :)
